PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl:     <http://www.w3.org/2002/07/owl#> 
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 

# show the two object "?device" "?sample" for : all ressource and the literal relation is contain between < and >
SELECT ?sample ?device
WHERE{
    ?row <http://inra/pegase#device> ?device .
    ?row <http://inra/pegase#sampleID> ?sample .
}

####### contain all type of relation ########
# xsd:string
# owl:AnnotationProperty
# rdfs:Class
# rdf:Property
# rdf:type
# rdf:resource
# a 